### ISSUE TITLE
Crash : ConcurrentModificationException

### ISSUE THREAD

**Issue by fleficher** [mg6maciej/android-maps-extensions#44]
Hi,

First, thank you for your library, it's really useful !

Since 2.3.0, I'm receiving some crashes from this library on Crashlytics :

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:788)
       at java.util.HashMap$KeyIterator.next(HashMap.java:815)
       at com.androidmapsextensions.impl.ClusterRefresher.refreshAll(ClusterRefresher.java:51)
       at com.androidmapsextensions.impl.ClusterRefresher$1.handleMessage(ClusterRefresher.java:31)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

I'm using version 10.0.1 from play-services-maps

**Comment by mg6maciej** [comment]
`ConcurrentModificationException` usually means a collection is modified from different threads. Is your application code calling all Google Maps API / Android Maps Extensions methods from main (UI) thread?

**Comment by fleficher** [comment]
Sorry for the delay. 
In fact, i couldn't reproduced the crash. So it's complicated to show an example of when the crash occurs.

The only thing i've changed is to use getExtendedMapAsync() instead of getExtendedMap().

Here is a sample of code that i'm using :


```
public class MyMapFragment extends SupportMapFragment
        implements GoogleMap.OnMarkerClickListener, OnMapReadyCallback {

   ...
    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        getExtendedMapAsync(this);
    }

    @Override
    public void onMapReady(GoogleMap googleMap) {
        if (!isAdded() || googleMap == null) {
            return;
        }
        mMap = googleMap;
        mMap.setClustering(new ClusteringSettings().enabled(true).addMarkersDynamically(true));
        mMap.setMapType(GoogleMap.MAP_TYPE_NORMAL);
        mMap.getUiSettings().setZoomControlsEnabled(true);
        mMap.getUiSettings().setZoomGesturesEnabled(true);
        mMap.setOnMarkerClickListener(this);
        mMap.setInfoWindowAdapter(new MarkerInfoWindowAdapter());
        mMap.setOnInfoWindowClickListener(new InfoWindowClickListener());
        if (mBitmapMarker == null) {
            mBitmapMarker = BitmapDescriptorFactory.fromResource(R.drawable.ic_map_pin);
        }
        initView();
    }

     private void initView() {
        if (mMap == null ) {
            //GoogleMap not initialized
            return;
        }
        try {
            mMap.clear();
            if (ArrayUtils.isEmpty(mPickupPoints)) {
                return;
            }
            for (PickupPoint pickupPoint : mPickupPoints) {
                addPointOfInterest(pickupPoint, new LatLng(pickupPoint.latitude, pickupPoint.longitude));
            }
            if (mUserPosition != null) {
                addMarker(mUserPosition, BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_AZURE), true);
                // zoom camera to marker
            } else {
                final LatLng pos = new LatLng(mPickupPoints.get(0).latitude, mPickupPoints.get(0).longitude);
                  // zoom camera to position
            }

        } catch (Exception ex) {
            LogUtils.logError(this, ex.getMessage());
        }
   ...
    }
```

**Comment by mg6maciej** [comment]
Is `onMapReady` the only place `initView` is called from?
What's the version of Google Play Services on devices you have this crash?
Does the crash completely disappear if you downgrade AME to 2.2.1?

**Comment by fleficher** [comment]
I call `initView` everyTime I need to update the map markers (from UI thread).
I'm using v10.0.1 of GPS.
Currently, I can't downgrade AME version. I will probably make a try in the future.

**Comment by mg6maciej** [comment]
Closing due to inactivity. Let me know if you can provide SSCCE of the issue.
